include:
  - proxy.yaml
services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"
    env_file:
      - path: web.env
    depends_on:
      - db

  db:
    image: mysql:8
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - path: .env
    ports:
      - "3306:3306"
