FROM python:3.9-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python3 -m venv venv
RUN . venv/bin/activate
EXPOSE 5000

CMD [ "python", "./main.py"]
